name: SimpleBackupKt
main: com.derppening.simplebackupkt.SimpleBackup
version: '2.0'
api-version: '1.16'

commands:
   sbackup:
      description: Run map backup
      usage: /sbackup

permissions:
   simplebackup.use:
      description: Run map backup
      default: op
