name: SimpleBackup
main: com.exolius.simplebackup.SimpleBackup
version: '1.8'
api-version: '1.16'

commands:
   sbackup:
      description: Run map backup
      usage: /sbackup

permissions:
   simplebackup.use:
      description: Run map backup
      default: op
